import { ToolInfo } from '@/types';

export const tools: ToolInfo[] = [
  {
    name: 'Merge PDF',
    slug: 'merge-pdf',
    description: 'Combine multiple files into one document',
    icon: 'merge',
    color: '',
  },
  {
    name: 'Split PDF',
    slug: 'split-pdf',
    description: 'Extract specific pages or split into separate files',
    icon: 'split',
    color: '',
  },
  {
    name: 'Compress PDF',
    slug: 'compress-pdf',
    description: 'Reduce file size while maintaining quality',
    icon: 'compress',
    color: '',
  },
  {
    name: 'PDF to Images',
    slug: 'pdf-to-images',
    description: 'Convert pages to PNG or JPG images',
    icon: 'image',
    color: '',
  },
  {
    name: 'Images to PDF',
    slug: 'images-to-pdf',
    description: 'Combine images into a single PDF',
    icon: 'imageToPdf',
    color: '',
  },
  {
    name: 'Rotate PDF',
    slug: 'rotate-pdf',
    description: 'Rotate pages by 90, 180, or 270 degrees',
    icon: 'rotate',
    color: '',
  },
  {
    name: 'Page Numbers',
    slug: 'add-page-numbers',
    description: 'Add page numbers to your document',
    icon: 'numbers',
    color: '',
  },
  {
    name: 'Reorder Pages',
    slug: 'reorder-pages',
    description: 'Rearrange pages in any order',
    icon: 'reorder',
    color: '',
  },
  {
    name: 'Sign PDF',
    slug: 'sign-pdf',
    description: 'Draw and place your signature on any page',
    icon: 'sign',
    color: '',
  },
  {
    name: 'Watermark',
    slug: 'add-watermark',
    description: 'Add a text watermark to every page',
    icon: 'watermark',
    color: '',
  },
  {
    name: 'Delete Pages',
    slug: 'delete-pages',
    description: 'Remove unwanted pages from your PDF',
    icon: 'delete',
    color: '',
  },
];
